---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datagen-app-deployment
spec:
  selector:
    matchLabels:
      app: datagen-app
  template:
    metadata:
      labels:
        app: datagen-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "datagen-app"
        dapr.io/config: dapr-crud-app
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: datagen-app
        image: docker.io/famargon/datagen-9b8bcb9dfb1aeb79acc402f8b9d5d0b3:latest
        imagePullPolicy: Always

