---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-replicas-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: zero-replicas-app
  template:
    metadata:
      labels:
        app: zero-replicas-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "zero-replicas-app"
        dapr.io/app-port: "8080"
        dapr.io/config: dapr-crud-app
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: crud-app
        image: docker.io/famargon/cmd-ccb721d992a9dd6158bf73b1f1bc6efb:latest
        imagePullPolicy: Always
        args:
          - "serve"
          - "-connStr"
          - "dapr"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: zero-replicas-app
spec:
  selector:
    app: zero-replicas-app
  type: ClusterIP
  ports:
  - name: http
    port:  8080
    targetPort:  8080

