---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "service-b"
        dapr.io/app-port: "8080"
        dapr.io/config: dapr-crud-app
        dapr.io/log-as-json: "false"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-cpu-request: "1m"
        dapr.io/sidecar-memory-request: "12Mi"
        dapr.io/sidecar-memory-limit: "29Mi"
    spec:
      containers:
      - name: service-b
        image: docker.io/famargon/service-b-7eda1c2433ddc30eb307d61d424e0e3a:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1m"
            memory: "972Ki"
          limits:
            memory: "6Mi"